package com.threeamigos.common.util.implementations.injection.cdi41tests.chapter5.par52typesaferesolution.ambiguityresolution.producerpriority;

public class ProducedByMethodPriorityService implements ResolutionServiceProducerPriority {
}
